//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesmentpaksod
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Answer()
        {
            this.T_Questionservay = new HashSet<T_Questionservay>();
        }
    
        public int Ans_Id { get; set; }
        public string Answer { get; set; }
        public int Sub_Id { get; set; }
        public string Sequence { get; set; }
    
        public virtual M_Subject M_Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Questionservay> T_Questionservay { get; set; }
    }
}
