//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesmentpaksod
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QuestionDetail
    {
        public int TQD_Id { get; set; }
        public int TQ_Id { get; set; }
        public int Sub_Id { get; set; }
    
        public virtual M_Subject M_Subject { get; set; }
        public virtual T_Question T_Question { get; set; }
    }
}
